version: 2

project_name: pomo

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^refactor:"
      - "^style:"
  groups:
    - title: 💥 Breaking Changes
      regexp: '^.*?(\w+(\([[:word:]]+\))?!:).+$'
      order: 0
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🐛 Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 🧹 Others
      order: 999

nfpms:
  - maintainer: Bahaa Mohamed <bahaa-dev@proton.me>
    description: A simple Pomodoro timer TUI application written in Go.
    homepage: https://github.com/Bahaaio/pomo
    license: MIT
    formats:
      - deb
      - rpm

release:
  github:
    owner: Bahaaio
    name: pomo
  name_template: "v{{.Version}}"
  footer: |
    ## Install

    ### Go
    ```bash
    go install github.com/Bahaaio/pomo@latest
    ```

    ### Download Binary
    Download from the assets below for your platform.

    ---
