name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"

      - name: Build
        run: go build -v ./...

  # skip tests for now
  # - name: Test
  #   run: go test -v ./...
